# -*- mode: python ; coding: utf-8 -*-


import os
spec_dir = os.path.dirname(os.path.abspath(SPEC))

a = Analysis(
    ['main.py'],
    pathex=[spec_dir],
    binaries=[],
    datas=[],
    hiddenimports=[
        'win32gui',
        'win32api',
        'win32con',
        'win32com.client',
        'winshell',
        'screen_brightness_control',
        'pywinstyles',
        'sv_ttk',
        'darkdetect',
        'pystray',
        'PIL',
        'appdirs',
        'json',
        'base64',
        'io',
        'lol',
        'lol.auto_accept',
        'lol.auto_pick',
        'lol.lcu_api',
        'settings',
        'brightness',
        'settings_window',
        'app',
        '_version',
        'urllib3',
        'requests',
        'lcu_driver',
        'asyncio',
        'aiohttp',
        'certifi',
    ],
    hookspath=[],
    hooksconfig={},
    runtime_hooks=[],
    excludes=[],
    noarchive=False,
)
pyz = PYZ(a.pure)

exe = EXE(
    pyz,
    a.scripts,
    a.binaries,
    a.datas,
    [],
    name='QOL-scripts',
    debug=False,
    bootloader_ignore_signals=False,
    strip=False,
    upx=False,
    upx_exclude=[],
    runtime_tmpdir=None,
    console=False,
    disable_windowed_traceback=False,
    argv_emulation=False,
    target_arch=None,
    codesign_identity=None,
    entitlements_file=None,
)
